### PR TITLE
Split code into separate files

### PR DESCRIPTION
**Pull request by samwebster**

### CODE REVIEW

**Review by siddharth-krishna — COMMENTED** [review]
Thanks for this, Sam! We definitely need some splitting and structuring. I had a few thoughts for discussion:

1. I'm a bit uncomfortable with wildcard imports, especially as we've taken the trouble to split our functions into meaningful modules. If the module names are too long we could e.g. `import .datatypes as dt`. From https://docs.python-guide.org/writing/structure/:
image

2. This nice SO answer talks about how to structure python projects that are meant to be executables/applications: https://stackoverflow.com/a/16745122/18619419
One of the things it recommends is to have different names for the script/executable and the module. Perhaps we can rename the script `read_times_excel.py`? Alternatively, we can do what `pip` does and have the script reside in `times_excel_reader/cli.py` and use setuptools to install our package with the following config in `setup.py:
```python
entry_points={
    'console_scripts': [
        'read_times_excel = times_excel_reader.cli:main',
    ],
},
```
But introducing setuptools/`setup.py` should probably be part of a separate PR.

Some references on this topic:
- https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application
- https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html#directory-layout

**Comment by samwebster** [comment]
Agree on 1. Will fix.

On 2, do we want people to have to install this to use it? One huge advantage of scripts is that they can just run. If so, it seems to make sense to have the script name the same as the repo so maybe we should change the top-level module name? Would it be very wrong to call it 'module' or 'ter'?

**Comment by siddharth-krishna** [comment]
Thanks, Sam. 

On the question of whether we want users to install this tool: I agree, it's nice to have scripts that can "just run", but that usually works best if it's a single self-contained file. I think once we have a multi-file python program, PYTHONPATH and relative/absolute imports come into the picture. I'm just cautious that we don't run into problems like the OP has in https://stackoverflow.com/q/16742203/18619419. Personally, I'm used to installing tools/applications via pip and then having them live on my PATH which makes it convenient to invoke them from the terminal from any directory (e.g. `jupyter`, `ipython`, even C++ tools like `onnx`).

On the question of names: I don't have a strong opinion, we could keep the script name as it is. The module could be called `times`, `pytimes`, `times_reader`, etc maybe? (maybe not `module` though, it might clash with some inbuilt python library).

(@olejandro , thoughts?)

**Comment by olejandro** [comment]
Good question! There is this one already which is basically a "code dump" at the moment: https://pypi.org/project/timeslib/
It would probably be best to involve the community on the naming issue... It may end up being an abbreviation of some sort... Maybe we could generate a few alternatives and make a poll?

**Comment by olejandro** [comment]
On the script / install issue, I am not sure that I understand the discussion completely 🤔 
I think it would be great to make the tool available via e.g. pip. It would be very convenient if one could both use the tool on its own, as well as integrate in other tools. However, would this imply a split into a library and an application?

**Comment by samwebster** [comment]
I've renamed the module and I think we're agreed that any changes around script vs installable should be another PR?

**Pull request merged**
